name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Check - black (formatting)
        run: black . --check

      - name: Check - isort (imports)
        run: isort . --check-only

      - name: Check - flake8 (lint)
        run: flake8 .

      - name: Tests - pytest
        run: pytest